"""
This is a setup.py script generated by py2applet

Usage:
    source .venv/bin/activate

then run:

    python setup.py py2app
"""
from setuptools import setup

APP = ['ai_whisperer.py']
DATA_FILES = []

OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'AiWhisperer.icns',
    # 1. CRITICAL: We EXCLUDE mlx so py2app doesn't break it by zipping it
    'excludes': ['mlx'], 
    # 2. We include the others normally
    'packages': ['rumps', 'pynput', 'parakeet_mlx', 'sounddevice', 'numpy', 'scipy'],
    # 3. We tell it to bundle the model folder we downloaded earlier
    # 'resources': ['model_weights'], 
    'plist': {
        'LSUIElement': True,
        'NSMicrophoneUsageDescription': 'AiWhisperer needs to hear you to type.',
        'NSAppleEventsUsageDescription': 'AiWhisperer needs to control the keyboard.',
        'LSEnvironment': {
            'LANG': 'en_US.UTF-8',
            'LC_ALL': 'en_US.UTF-8',
        },
    }
}

setup(
    app=APP,
    name='AiWhisperer',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)